Task 1: Try the algo on Same Whether dataset - OneHotEncoding of features: and Train test Division 75%-25%

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [ ]:
#Predictor variables
Outlook = ['Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Sunny', 'Overcast',
            'Rainy', 'Rainy', 'Sunny', 'Rainy','Overcast', 'Overcast', 'Sunny']
Temperature = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool',
                'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
Humidity = ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal',
            'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High']
Wind = ['False', 'True', 'False', 'False', 'False', 'True', 'True',
            'False', 'False', 'False', 'True', 'True', 'False', 'True']

#Class Label:
Play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No',
'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

In [ ]:
dataset_list = list(zip(Outlook, Temperature, Humidity, Wind, Play))
dataset = pd.DataFrame(dataset_list, columns = ["Outlook", "Temperature", "Humidity", "Wind", "Play"])
print("Number of examples and feature:", dataset.shape)
dataset.head()

Number of examples and feature: (14, 5)


Outlook Temperature Humidity   Wind Play
0     Rainy         Hot     High  False   No
1     Rainy         Hot     High   True   No
2  Overcast         Hot     High  False  Yes
3     Sunny        Mild     High  False  Yes
4     Sunny        Cool   Normal  False  Yes

In [ ]:
dataset.describe()

Outlook Temperature Humidity   Wind Play
count       14          14       14     14   14
unique       3           3        2      2    2
top      Sunny        Mild   Normal  False  Yes
freq         5           6        7      8    9

In [ ]:
dummy = pd.get_dummies(dataset.iloc[:,:-1])

cols = dataset.columns.tolist()
cols.remove("Play")

dataset = dataset.drop(cols, axis = 1)
dataset = pd.concat([dummy,dataset], axis = 1)

print("\n\nFinal dataset :\n")
dataset.head()



Final dataset :



Outlook_Overcast  Outlook_Rainy  Outlook_Sunny  ...  Wind_False  Wind_True  Play
0                 0              1              0  ...           1          0    No
1                 0              1              0  ...           0          1    No
2                 1              0              0  ...           1          0   Yes
3                 0              0              1  ...           1          0   Yes
4                 0              0              1  ...           1          0   Yes

[5 rows x 11 columns]

In [ ]:
print("\nLabel")
labels = dataset['Play']
labels


Label


0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play, dtype: object

In [ ]:
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(dataset.iloc[:,:-1],
                        labels, test_size = 0.25, random_state = 80)

In [ ]:
DT = DecisionTreeClassifier(max_leaf_nodes = 80, random_state = 80)

# fitting the model or training
final_model = DT.fit(data_train,target_train)

In [ ]:
# testing
target_predict = DT.predict(data_test)

In [ ]:
# Accuracy
Accuracy = accuracy_score(target_test, target_predict)
print("Accuracy:", Accuracy)

Accuracy: 0.25


In [ ]:
# Confusion Matrix
cm = confusion_matrix(target_test, target_predict)
print("Confusion Matrix:\n")
cm

Confusion Matrix:



array([[0, 3],
       [0, 1]])

In [ ]:
# Precision
precision = precision_score(target_test, target_predict, average=None)
print("Precision:\n")
precision

Precision:



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0.  , 0.25])

In [ ]:
# Recall
recall = recall_score(target_test, target_predict, average=None)
print("Recall:\n")
recall

Recall:



array([0., 1.])

In [ ]:
# (1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

q1 = [0,1,0,0,0,1,0,1,1,0] # Overcast Rainy Sunny Cool Hot Mild High Normal False True

# (2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

q2 = [0,0,1,1,0,0,1,0,0,1] # Overcast Rainy Sunny Cool Hot Mild High Normal False True

In [ ]:
features = dataset.columns.tolist()
features.remove("Play")
df = pd.DataFrame([q1,q2], columns = features)
df.head()

Outlook_Overcast  Outlook_Rainy  ...  Wind_False  Wind_True
0                 0              1  ...           1          0
1                 0              0  ...           0          1

[2 rows x 10 columns]

In [ ]:
ans = DT.predict(df)
print("Play predicted:\nq1: {}\nq2: {}".format(ans[0],ans[1]))

Play predicted:
q1: Yes
q2: No
