In [17]:
import numpy as np

## Training Data

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [19]:
# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print(weights)
print(biases)

[[0.12681175 0.41239176 0.18767353]
 [0.40309149 0.6357669  0.77966749]]
[[0.57377739 0.62395873]
 [0.08532309 0.61141821]
 [0.23027467 0.15709618]
 [0.23192968 0.10731081]
 [0.0398175  0.48587399]
 [0.36994667 0.06311568]
 [0.26854864 0.29984765]
 [0.85482593 0.14092623]
 [0.03000705 0.47195841]
 [0.18100488 0.83166247]
 [0.45293735 0.73095578]
 [0.13247876 0.64571766]
 [0.22800662 0.13757452]
 [0.98772722 0.86714388]
 [0.73169109 0.29564269]]


In [20]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [21]:
# Generate predictions
preds = model(inputs)


In [22]:
# Compare with targets
print("Predictions : ", preds)
print("Targets : ",targets)

Predictions :  [[ 45.53124436 106.17172191]
 [ 59.92677251 143.13895041]
 [ 77.40845676 165.63953508]
 [ 37.84349394  97.40831652]
 [ 61.51658372 143.90953361]
 [ 45.32741364 105.61087886]
 [ 60.10999805 142.82737985]
 [ 78.03300802 165.62336513]
 [ 37.64157131  97.77296411]
 [ 61.6577711  144.2553221 ]
 [ 45.41040432 106.27871896]
 [ 59.97392817 143.17324986]
 [ 77.40618871 165.62001343]
 [ 38.59929148  98.16814959]
 [ 62.20845732 143.71930231]]
Targets :  [[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


## Loss function

In [23]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [24]:
# Compute loss
loss = mse(preds, targets)
print(loss)

2533.6803276309874


## Compute Gradient

In [25]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print(weights_grad)
print(biases_grad)

[[-2996.61607833 -4547.34246172 -2596.08848661]
 [ 6886.61872043  6198.21420928  4051.41317956]]
[[-1.39583409  4.82289625]
 [-2.80976367  5.61852672]
 [-5.5455391   4.35193801]
 [ 2.11246586  8.0544422 ]
 [-5.53112217  3.32127115]
 [-1.42301151  4.74811718]
 [-2.78533359  5.57698398]
 [-5.4622656   4.34978202]
 [ 2.08554284  8.10306188]
 [-5.51229719  3.36737628]
 [-1.41194609  4.83716253]
 [-2.80347624  5.62309998]
 [-5.54584151  4.34933512]
 [ 2.21323886  8.15575328]
 [-5.43887236  3.29590698]]


## Adjust weights

In [26]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [27]:
print(weights)
print(biases)

[[0.15677791 0.45786518 0.21363441]
 [0.3342253  0.57378476 0.73915336]]
[[0.57379135 0.6239105 ]
 [0.08535119 0.61136202]
 [0.23033013 0.15705266]
 [0.23190855 0.10723027]
 [0.03987281 0.48584078]
 [0.3699609  0.0630682 ]
 [0.26857649 0.29979188]
 [0.85488056 0.14088273]
 [0.02998619 0.47187738]
 [0.18106    0.8316288 ]
 [0.45295147 0.73090741]
 [0.13250679 0.64566143]
 [0.22806208 0.13753103]
 [0.98770508 0.86706232]
 [0.73174548 0.29560973]]


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1392.8043632150127


In [29]:
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

14.172238156271673


In [31]:
# Print predictions
print(preds)

[[ 58.10690576  71.08183444]
 [ 80.32620785 100.08229547]
 [121.07041873 133.58168895]
 [ 24.60658136  39.46292946]
 [ 96.74449888 116.31789167]
 [ 57.90312967  70.52114168]
 [ 80.5093843   99.7708084 ]
 [121.69480263 133.56552334]
 [ 24.40471284  39.82747935]
 [ 96.88564843 116.6635875 ]
 [ 57.9860981   71.18880282]
 [ 80.37335088 100.11658573]
 [121.06815128 133.56217253]
 [ 25.36217637  40.22255892]
 [ 97.43618708 116.12771135]]


In [32]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
